// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDolMgTX4RPTgLGrZJIqOoRKZp8YC7Nvgw',
    appId: '1:1069269033558:web:7159a850f93c75234491f7',
    messagingSenderId: '1069269033558',
    projectId: 'mp-win',
    authDomain: 'mp-win.firebaseapp.com',
    storageBucket: 'mp-win.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARme6SNUC4XEndlvmqhEy6RronqoSQX5U',
    appId: '1:1069269033558:android:9803727aecf8b2d34491f7',
    messagingSenderId: '1069269033558',
    projectId: 'mp-win',
    storageBucket: 'mp-win.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavMMn-syZLiPz4QsrvQrx-f6PexVawCg',
    appId: '1:1069269033558:ios:b4ec450ef8b25a964491f7',
    messagingSenderId: '1069269033558',
    projectId: 'mp-win',
    storageBucket: 'mp-win.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBavMMn-syZLiPz4QsrvQrx-f6PexVawCg',
    appId: '1:1069269033558:ios:9b0d73ff3ff8db7c4491f7',
    messagingSenderId: '1069269033558',
    projectId: 'mp-win',
    storageBucket: 'mp-win.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
